import Foundation
import Testing
@testable import SusurroCore

/// Golden tests. Expected outputs were generated by running the actual Python
/// `apply_verbal_punctuation` from ptt/nemo_itn_daemon.py (2026-07-12), except the
/// two documented divergences at the bottom ("new line" and "backslash", both of
/// which were latent bugs in the Python version).
@Suite struct PostProcessorGoldenTests {
    /// Bundled default rules only — never the developer's personal user file.
    private func makeProcessor() -> PostProcessor {
        let missing = FileManager.default.temporaryDirectory
            .appendingPathComponent("susurro-tests-\(UUID().uuidString)/rules.json")
        return PostProcessor(userRulesURL: missing) // falls back to bundled defaults
    }

    // MARK: Python parity

    static let pythonParityCases: [(input: String, expected: String)] = [
        ("Add a comment that says, quote, this is a temporary work around, end quote, then file a ticket period",
         "Add a comment that says \"this is a temporary work around\" then file a ticket."),
        ("Then file a ticket period.",
         "Then file a ticket."),
        ("hello world comma how are you question mark",
         "Hello world, how are you?"),
        ("this is great exclamation point",
         "This is great!"),
        ("quote to be or not to be end quote comma that is the question period",
         "\"to be or not to be\", that is the question."),
        ("no triggers here just a normal sentence.",
         "No triggers here just a normal sentence."),
        ("full stop",
         "."),
        ("she said quote, hello there, end quote. and left",
         "She said \"hello there\" and left"),
        ("already capitalized sentence period",
         "Already capitalized sentence."),
        ("multiple spaces   between    words comma weird",
         "Multiple spaces between words, weird"),
    ]

    @Test(arguments: pythonParityCases.indices)
    func pythonParity(index: Int) {
        let (input, expected) = Self.pythonParityCases[index]
        #expect(makeProcessor().process(input) == expected)
    }

    // MARK: Documented divergences from Python (bug fixes)

    @Test func newLineActuallyInsertsNewline() {
        // Python golden was "First line second line" — its whitespace collapse
        // destroyed the newline it had just inserted.
        #expect(makeProcessor().process("first line new line second line")
                == "First line\nsecond line")
    }

    @Test func backslashInsertsSingleBackslash() {
        // Python golden was "Use a \\\\ to escape it" (two backslashes).
        #expect(makeProcessor().process("use a backslash to escape it")
                == "Use a \\ to escape it")
    }

    // MARK: New capabilities

    @Test func disabledRuleIsInert() throws {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("susurro-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appendingPathComponent("rules.json")
        try """
        {
            "options": { "pairQuotes": true, "autoCapitalize": false, "normalizeWhitespace": true },
            "punctuation": [ { "say": "comma", "insert": ",", "enabled": false } ],
            "substitutions": [],
            "regexRules": []
        }
        """.write(to: url, atomically: true, encoding: .utf8)
        let processor = PostProcessor(userRulesURL: url)
        #expect(processor.process("one comma two") == "one comma two")
    }

    @Test func substitutionFixesJargon() throws {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("susurro-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appendingPathComponent("rules.json")
        try """
        {
            "options": { "pairQuotes": true, "autoCapitalize": true, "normalizeWhitespace": true },
            "punctuation": [],
            "substitutions": [ { "match": "launch DP list", "replace": "launchd plist" } ],
            "regexRules": []
        }
        """.write(to: url, atomically: true, encoding: .utf8)
        let processor = PostProcessor(userRulesURL: url)
        #expect(processor.process("update the launch DP list and rebuild")
                == "Update the launchd plist and rebuild")
    }

    @Test func invalidUserFileFallsBackToDefaults() throws {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("susurro-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appendingPathComponent("rules.json")
        try "{ this is not json".write(to: url, atomically: true, encoding: .utf8)
        let processor = PostProcessor(userRulesURL: url)
        #expect(processor.process("hello comma world") == "Hello, world")
    }
}
